name: Test duatic_simulation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    # Use your custom ROS Docker image
    container:
      image: ghcr.io/duatic/duatic_docker_image:1.0.21
      options: --user root  # optional, only if you need root

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Build the duatic_simulation package temporarily
      - name: Build workspace
        shell: bash
        run: |
          source /opt/ros/jazzy/setup.bash
          colcon build --packages-select duatic_simulation --event-handlers console_cohesion+

      # Run tests for duatic_simulation
      - name: Run tests
        shell: bash
        run: |
          source install/setup.bash
          colcon test --packages-select duatic_simulation --event-handlers console_direct+
          colcon test-result --verbose

      # Upload test logs (optional)
      - name: Upload test logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: duatic_test_logs
          path: |
            log/
            build/**/test_results/
            install/**/test_results/
